---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  modules_path: nevermind
  resolve_with_librarian_puppet: true
  require_chef_for_busser: true

platforms:
  - name: puppetlabs/centos-6.6-64-puppet
    driver_plugin: vagrant
    driver_config:
      box: puppetlabs/centos-6.6-64-puppet

suites:
  - name: default
