rvm: 1.9.3

env:
  - PUPPET_VERSION=3.7
  - PUPPET_VERSION=4.0

script:
  - bundle exec rake lint
  - bundle exec rake validate
  - bundle exec rake spec

before_deploy:
  - bundle exec rake clean
  - bundle exec rake set_travis_version

deploy:
  skip_cleanup: true
  provider: puppetforge
  user:
    secure: "atI1t+ELd3uJJTtt75s9rMDjdiIEHLiHvwOhlJe1sLAAQ6WegbFqoVwje+FVUH9QYRVKcfO3T4nMZLyXqj33PyH7xzVN9hChMhM8qCN397idowjZA66/8jK7oPN2TRX4/z2kvEpw8i5nOa46ALEjYfi0HK8nFtZGr+SGjUpt7Yg6KrHaXQwJP0RmEG22m/j83wZ8ZD/vNsBGAACHn0Ago3MVieCMfC31u7d0181Nk02dU3q3xdiN8WrbnhiIoqIUJN3KRnakhXLJNZKh7YYT1V/9JczpIGjxBfGRfxSCTYwPmz68799mpNgeoZJrg/aX/BoQDDDJzBGW5bJzH7guhb5zssyFtDfnThhU8DCRSgkQIT6Py3SPPpoqWh7pAyhvQ7IKWzm58gB/pWWpAcpOK/DPE8kDlSaE5YgTyogsER47/wapCNxelMD07UaFh6fkbNDCEaB6zt7vDkuiLuuRnk3n8U4k++5k8czXk6cTQloh7xo6OgMnc4He+eji+d32NckTOfe3P8NWm4HWw6PuwzqM2ONtV/pr0rSPgKdq0KWX3USr2JgGF0nmSiH5izl3xYj6NFFx6cc3+egv0/m7LdVcp4z41GdyGmM43XnF7wfVfi4td7+bixqOer/+AhRxDPSor1iT4bQNtDXkipHurF6H6e3v/aJECc7YHQrq3HA="

  password:
    secure: "crzi/hhIjETQ1TMo8MdPlyjqn+ZXDDlZKhId9pSI5uekgAdUcRYZ1Qr9BPp9Lm5XgMYkv7j0peEK9j90NOGiBl/oGtWOeEBf1F0KbfF9iBbksEeOjHbHxn1NXi7bCZLIDZT5kCHa061Rq7ScNgzTcXFclM5nwWJ115QtcT/0ykQ02sj4oCwWmaJL0C/CtmeBfHJogc5g0j+1T0MeOxypS/TTmg7vHw28ZP90qV6GCYZvfyiurglzDgrSyBsSBXyjQS9cWR/0UHR1BGo/r3Q6IAwmcJTI+Yxk8d3RRsWrLMGGUlFjA2y4Er4p35sD96esHQaWvrHWJidZwxxqBCgNahNN4wZpeEa402LQ03k6ZtlrwtsoRNAK+aUhqMa8ulGlayF61oBNC4l1pnH2aOTBN9ZFelL3EPATya/+Ob6khTqeVObMWrTcVIdxkgzfUpuyWu9L1OxxN89svTD93xXzfiO4pSeu6KMvzOXwbByUfmjrz8AnJfPmnyN5Jqo84qugkczwdZQQn9fzrNX4Tl34ahLrjjGjTl7P3zxx3a1N+ZmsS2q96TJcZlPsrOkpwwOu/Z4/UPuODgdn1vpXYgRBp8VUIIWBC/j4C336xpIrBF6iYGqhtGI+d+iQV42PsQy9jVDNkDWAUE1uSQBKqxcFEWDUBZRXO4l5HqvescNjyVA="
